name: text_parser
description: A Dart package for flexibly parsing text into easy-to-handle format according to multiple regular expression patterns.
version: 2.4.0
repository: https://github.com/kaboc/dart_text_parser

topics:
  - text
  - parser
  - parsing

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  meta: ^1.10.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.7
