name: text_parser
description: A Dart package for flexibly parsing text into easy-to-handle format according to multiple regular expression patterns.
version: 0.4.2
repository: https://github.com/kaboc/dart_text_parser

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  meta: ^1.7.0

dev_dependencies:
  lints: ^2.0.1
  test: ^1.21.4
