name: text_parser
description: A Dart package for parsing text flexibly according to preset or custom regular expression patterns.
version: 0.3.1
repository: https://github.com/kaboc/dart_text_parser

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  meta: ^1.7.0

dev_dependencies:
  test: ^1.19.5
