name: text_parser
description: A Dart package for parsing text flexibly according to preset or custom regular expression patterns.
version: 0.1.1-nullsafety.1
homepage: https://github.com/kaboc/dart_text_parser

environment:
  sdk: '>=2.12.0-29.10.beta <3.0.0'

dependencies:
  meta: ^1.3.0

dev_dependencies:
  test: ^1.16.2
