name: Dart CI

on:
  push:
    branches: [main]
  pull_request:
    tags: [opened, synchronize]
  workflow_dispatch:

jobs:
  dart-ci:
    runs-on: ubuntu-latest

    container:
      image: google/dart:latest

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: pub get
      - name: Format
        run: dartfmt -n --set-exit-if-changed .
      - name: Analyze
        run: dartanalyzer --fatal-warnings --fatal-infos .
      - name: Analyze examples
        run: dartanalyzer --fatal-warnings --fatal-infos example
      - name: Run tests
        run: pub run test
