name: Dart CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  dart-ci:
    runs-on: ubuntu-latest

    container:
      image: google/dart:latest

    steps:
      - uses: actions/checkout@v2
      - run: dart pub get
      - run: dart format --output none --summary none  --set-exit-if-changed .
      - run: dart analyze --fatal-warnings --fatal-infos .
      - run: dart pub run test
